apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restored-mongodb-pvc
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: mongodb-data-snapshot-20240522044918
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi