apiVersion: mirrors.kts.studio/v1alpha2
kind: SecretMirror
metadata:
  name: prometheus-credentials
  namespace: external-secret
spec:
  source:
    name: prometheus-password
  destination:
    namespaces:
      - mongodb
      - prometheus