apiVersion: mirrors.kts.studio/v1alpha2
kind: SecretMirror
metadata:
  name: atlas-api-credentials
  namespace: external-secret
spec:
  source:
    name: atlas-api-secret
  destination:
    namespaces:
      - mongodb