apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: external-secret
spec:
  provider:
    # https://external-secrets.io/latest/provider/aws-secrets-manager/
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: accessKeyID
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secretAccessKey