# https://www.mongodb.com/docs/kubernetes-operator/upcoming/tutorial/cert-manager-integration/#create-certificates-for-your-mongodb-resources
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rs-0-certificate
  namespace: mongodb
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  dnsNames:
  - rs-0-0
  - rs-0-0.rs-0-svc.mongodb.svc.cluster.local
  - rs-0-1
  - rs-0-1.rs-0-svc.mongodb.svc.cluster.local
  - rs-0-2
  - rs-0-2.rs-0-svc.mongodb.svc.cluster.local
  - rs-0-3
  - rs-0-3.rs-0-svc.mongodb.svc.cluster.local
  - localhost
  duration: 240h0m0s
  issuerRef:
    name: mongodb-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  renewBefore: 120h0m0s
  secretName: mdb-rs-0-cert
  usages:
  - server auth
  - client auth