# https://www.mongodb.com/docs/kubernetes-operator/upcoming/tutorial/cert-manager-integration/#create-certificates-for-your-mongodb-resources
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: agent-certs
  namespace: mongodb
spec:
  secretName: mdb-rs-0-agent-certs
  commonName: automation
  dnsNames:
  - automation
  duration: 240h0m0s
  issuerRef:
    name: mongodb-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  renewBefore: 120h0m0s
  usages:
  - digital signature
  - key encipherment
  - client auth
  subject:
    countries:
    - US
    localities:
    - NY
    organizationalUnits:
    - a-1635241837-m5yb81lfnrz
    organizations:
    - cluster.local-agent
    provinces:
    - NY